#%RAML 0.8
title: HATEOAS Inc. Example API
version: v1
baseUri: http://hateoas-example.skqr.net/app_dev.php/api/{version}
mediaType: application/vnd.api+json
schemas:
  - some-resources: !include some-resources.schema.json
resourceTypes:
  - collection:
      get:
        responses:
          200:
            body:
              schema: <<resourcePathName>> # e.g. users
      post:
        responses:
          200:
            body:
              schema: <<resourcePathName | !singularize>>  # e.g. user
  - member:
      get:
        responses:
          200:
            body:
              schema: <<resourcePathName>> # e.g. user
traits:
  - !include some-traits.yml
  - secured:
      description: Some requests require authentication
      queryParameters:
        <<methodName>>: # e.g. get:
          description: A <<methodName>> name-value pair must be provided for this request to succeed.  # e.g. A get name-value...
          example: <<methodName>>=h8duh3uhhu38   # e.g. get=h8duh3uhhu38
/some-resources:
  displayName: Random resources
  get:
    description: Retrieves one or more random resources.
    is: [paginated]
    responses:
      200:
  post:
    description: Creates one or more random resources.
    responses:
      201:
  /{some-resources-ids}:
    get:
      description: Retrieves one or more random resources.
      responses:
        200:
    put:
      description: Updates one or more random resources.
      responses:
        204:
    delete:
      description: Deletes one or more random resources.
